namespace DhubSolutions.Reports.Domain.Entities.DataUploader.DataRow
{
    public class MonthlyLNetAccountWorkspace
    {
        public long AccountId { get; set; }
        public string AccountName { get; set; }
        public string OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public string WorkspaceId { get; set; }
        public string PeriodId { get; set; }
        public string DataLevelName { get; set; }
        public long DataLevelId { get; set; }
        public double? TotalOperatingPerformanceOid2458859 { get; set; }
        public double? IShareCapital { get; set; }
        public double? IiTangibleAssets { get; set; }
        public double? TaxOnProfit { get; set; }
        public double? OtherOperatingExpenses { get; set; }
        public double? CapitalTurnoverOid2458802 { get; set; }
        public double? UrlaubstageIn { get; set; }
        public double? KeyFiguresOnFinanceAndLiquidity { get; set; }
        public double? EmployeesFte { get; set; }
        public double? GrossMarginOid2461277 { get; set; }
        public double? StaticDebtEquityRatio { get; set; }
        public double? FlowToEquity { get; set; }
        public double? PersonalExpenseRatio { get; set; }
        public double? _3PaymentsReceivedOnAccountOfOrdersOid2400241 { get; set; }
        public double? ViAusgleichspostenFürAnteileAndererGesellschafter { get; set; }
        public double? EbitdaMargin { get; set; }
        public double? Assets { get; set; }
        public double? EbitEarningsBeforeInterestAndTaxes { get; set; }
        public double? EbtEarningsBeforeTaxes { get; set; }
        public double? _8OtherLiabilities { get; set; }
        public double? Staff { get; set; }
        public double? ShortTermClaims { get; set; }
        public double? AStockholdersEquity { get; set; }
        public double? DDeferredTaxAssets { get; set; }
        public double? DebtRatio { get; set; }
        public double? IntensityOfReceivables { get; set; }
        public double? CasfhFlowFromOperatingActivities { get; set; }
        public double? DepreciationOid2458781 { get; set; }
        public double? _2ndDegreeLiquidity { get; set; }
        public double? GrossMarginOid2468554 { get; set; }
        public double? IvKonzernergebnisvortrag { get; set; }
        public double? ProfitTurnoverRatioOid2458861 { get; set; }
        public double? TotalOperatingPerformanceOid2458745 { get; set; }
        public double? MaterialExpenseRatioYtd { get; set; }
        public double? ProfitFromOperations { get; set; }
        public double? ProfitTurnoverRatioOid2458951 { get; set; }
        public double? InterestExpense { get; set; }
        public double? KrankheitstageIn { get; set; }
        public double? InventoryRatio { get; set; }
        public double? MaterialIntensity { get; set; }
        public double? Ebit { get; set; }
        public double? ReturnOnEquityOid2458950 { get; set; }
        public double? MaterialExpenseRatio { get; set; }
        public double? IiCapitalReserves { get; set; }
        public double? IIntangibleAssets { get; set; }
        public double? CurrentAccountOverdraft { get; set; }
        public double? _6LiabilitiesToSubsidiariesAndAffiliatedCompaniesOid12745 { get; set; }
        public double? PersonalIntensityYtd { get; set; }
        public double? CurrencyAdjustment { get; set; }
        public double? _1AccountsReceivableTrade { get; set; }
        public double? CashFlowFromFinancingActivities { get; set; }
        public double? MaterialIntensityRatioYtd { get; set; }
        public double? Equity { get; set; }
        public double? NetSales { get; set; }
        public double? IiiFinancialAssets { get; set; }
        public double? TotalOperatingPerformanceOid2458799 { get; set; }
        public double? AverageCommittedCapitalOid2458800 { get; set; }
        public double? OrdersInHand { get; set; }
        public double? CurrentAssetsToTotalAssets { get; set; }
        public double? EquityRatio { get; set; }
        public double? OtherOperatingIncome { get; set; }
        public double? EgtMargin { get; set; }
        public double? VBalanceSheetProfitLoss { get; set; }
        public double? CurrentAssets { get; set; }
        public double? Orders { get; set; }
        public double? _1stDegreeLiquidity { get; set; }
        public double? EquityAndLiabilities { get; set; }
        public double? CashFlowToEquity { get; set; }
        public double? Personalaufwandsquote { get; set; }
        public double? NetWorkingCapital { get; set; }
        public double? EEarnings { get; set; }
        public double? PersonalExpenseRatioYtd { get; set; }
        public double? Ebt { get; set; }
        public double? IntensityOfInvestments { get; set; }
        public double? CashFlowFromInvestingActivities { get; set; }
        public double? IiiRevenueReserves { get; set; }
        public double? KpiOnlyUsedForSingleEntities { get; set; }
        public double? CashFlow { get; set; }
        public double? BCurrentAssets { get; set; }
        public double? EbitMargin { get; set; }
        public double? ShortTermLiabilities { get; set; }
        public double? _3rdDegreeLiquidity { get; set; }
        public double? CapitalTurnoverOid2458864 { get; set; }
        public double? _4AccountsPayableTradeOid12741 { get; set; }
        public double? DuPont { get; set; }
        public double? AFixedAssetsOid12623 { get; set; }
        public double? OtherTaxes { get; set; }
        public double? EbtMargin { get; set; }
        public double? TaxesOnIncome { get; set; }
        public double? LiquidAssets { get; set; }
        public double? ResultFromOrdinaryOperationsOid2458754 { get; set; }
        public double? DAccountsPayable { get; set; }
        public double? LabourExpenses { get; set; }
        public double? EMargin { get; set; }
        public double? GrossProfit { get; set; }
        public double? IInventories { get; set; }
        public double? NumberOfStaffIllFte { get; set; }
        public double? ProductionForOwnFixedAssetsCapitalized { get; set; }
        public double? ResultFromOrdinaryOperationsOid2458778 { get; set; }
        public double? NetIncomeNetLossForTheFinancialYear { get; set; }
        public double? PersonalIntensity { get; set; }
        public double? CostOfMaterials { get; set; }
        public double? FixedAssets { get; set; }
        public double? OverallEquipmentEffectiveness { get; set; }
        public double? IiReceivablesAndOtherAssets { get; set; }
        public double? CPrepaidExpenses { get; set; }
        public double? NewOrders { get; set; }
        public double? IncreaseDecreaseInFinishedGoodsAndWorkInProgress { get; set; }
        public double? EbitdaEarningsBeforeInterestTaxesDepreciationAndAmortization { get; set; }
        public double? ProfitTurnoverRatioOid2458863 { get; set; }
        public double? ReturnOnEquityOid2458970 { get; set; }
        public double? DepreciationOid2458750Ref12867 { get; set; }
        public double? EDeferredIncome { get; set; }
        public double? KeyFiguresOnTheAssetAndEquityStructure { get; set; }
        public double? TradeReceivables { get; set; }
        public double? EarningsBeforeIncomeTaxes { get; set; }
        public double? RoiReturnOnInvestment { get; set; }
        public double? FinancialResult { get; set; }
        public double? AverageCommittedCapitalOid2458797 { get; set; }
        public double? CProvisions { get; set; }
        public double? KeyFiguresOnExpenseAndIncomeStructure { get; set; }
        public double? ExtraordinaryResult { get; set; }
        public double? NumberOfStaffInHolidaysFte { get; set; }
        public double? KeyFiguresOnTheIncomeSituation { get; set; }
        public double? Loans { get; set; }
        public double? TradePayables { get; set; }
        public double? ExtraordinaryResults { get; set; }
        public double? Provisions { get; set; }
        public double? Materialaufwandsquote { get; set; }
        public double? IvChecksCashAtBankAndInHand { get; set; }
        public int ViAdvancePaymentsFromCustomers { get; set; }
        public int Verschuldungsgrad { get; set; }
        public int Schuldendienstdeckungsgrad { get; set; }
        public int IiiSecurities { get; set; }
        public int IvShareholderLoan { get; set; }
    }
}
